/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** QR code validation result */
export interface ValidationResult {
  /** Scannability score from 0-100 */
  score: number
  /** Whether the QR code was successfully decoded */
  decodable: boolean
  /** Decoded content of the QR code */
  content?: string
  /** QR code version (1-40) */
  version?: number
  /** Error correction level (L, M, Q, H) */
  errorCorrection?: string
  /** Number of modules in the QR code */
  modules?: number
  /** List of decoders that successfully decoded the QR */
  decodersSuccess: Array<string>
  /** Whether original image was decodable */
  stressOriginal: boolean
  /** Whether 50% downscaled image was decodable */
  stressDownscale50: boolean
  /** Whether 25% downscaled image was decodable */
  stressDownscale25: boolean
  /** Whether lightly blurred image was decodable */
  stressBlurLight: boolean
  /** Whether medium blurred image was decodable */
  stressBlurMedium: boolean
  /** Whether low contrast image was decodable */
  stressLowContrast: boolean
}
/** Simple decode result (without stress tests) */
export interface DecodeResult {
  /** Decoded content of the QR code */
  content: string
  /** QR code version (1-40) */
  version?: number
  /** Error correction level (L, M, Q, H) */
  errorCorrection?: string
  /** Number of modules in the QR code */
  modules?: number
}
/**
 * Validate a QR code image and compute scannability score
 *
 * @param imageBuffer - Raw image bytes (PNG, JPEG, etc.)
 * @returns ValidationResult with score, content, and metadata
 */
export declare function validate(imageBuffer: Buffer): ValidationResult
/**
 * Fast decode without stress tests (for when you only need content)
 *
 * @param imageBuffer - Raw image bytes (PNG, JPEG, etc.)
 * @returns DecodeResult with content and basic metadata
 */
export declare function decode(imageBuffer: Buffer): DecodeResult
/**
 * Fast validation with reduced stress tests (~2x faster)
 *
 * Good for real-time feedback during QR editing.
 *
 * @param imageBuffer - Raw image bytes (PNG, JPEG, etc.)
 * @returns ValidationResult with score, content, and metadata
 */
export declare function validateFast(imageBuffer: Buffer): ValidationResult
/**
 * Get only the scannability score (0-100)
 *
 * @param imageBuffer - Raw image bytes (PNG, JPEG, etc.)
 * @returns Score from 0 (unreadable) to 100 (highly scannable)
 */
export declare function validateScoreOnly(imageBuffer: Buffer): number
/**
 * Get score using fast validation (~2x faster)
 *
 * @param imageBuffer - Raw image bytes (PNG, JPEG, etc.)
 * @returns Score from 0 (unreadable) to 100 (highly scannable)
 */
export declare function validateScoreFast(imageBuffer: Buffer): number
/** Simple summary of QR validation */
export interface QrSummary {
  /** Whether the QR is valid and decodable */
  valid: boolean
  /** Scannability score (0-100) */
  score: number
  /** Decoded content (empty if invalid) */
  content: string
  /** Error correction level (L/M/Q/H or "N/A") */
  errorCorrection: string
  /** Human-readable rating (Excellent/Good/Fair/Poor) */
  rating: string
  /** Whether this QR is production-ready (score >= 70) */
  productionReady: boolean
}
/**
 * Check if QR code is valid (returns content or null)
 *
 * @example
 * ```typescript
 * const content = isValid(buffer);
 * if (content) {
 *   console.log(`QR contains: ${content}`);
 * }
 * ```
 *
 * @param imageBuffer - Raw image bytes (PNG, JPEG, etc.)
 * @returns Decoded content string, or null if QR is invalid
 */
export declare function isValid(imageBuffer: Buffer): string | null
/**
 * Get scannability score (0-100)
 *
 * @example
 * ```typescript
 * const s = score(buffer);
 * console.log(`Scannability: ${s}/100`);
 * ```
 *
 * @param imageBuffer - Raw image bytes (PNG, JPEG, etc.)
 * @returns Score from 0 (unreadable) to 100 (highly scannable)
 */
export declare function score(imageBuffer: Buffer): number
/**
 * Check if QR meets minimum score threshold
 *
 * @example
 * ```typescript
 * if (passesThreshold(buffer, 70)) {
 *   console.log('Production ready!');
 * }
 * ```
 *
 * @param imageBuffer - Raw image bytes (PNG, JPEG, etc.)
 * @param minScore - Minimum score required (0-100)
 * @returns true if score >= minScore
 */
export declare function passesThreshold(imageBuffer: Buffer, minScore: number): boolean
/**
 * Get production readiness (score >= 70)
 *
 * @example
 * ```typescript
 * if (isProductionReady(buffer)) {
 *   await uploadQr(buffer);
 * }
 * ```
 *
 * @param imageBuffer - Raw image bytes (PNG, JPEG, etc.)
 * @returns true if QR is production-ready
 */
export declare function isProductionReady(imageBuffer: Buffer): boolean
/**
 * Get simple summary of QR validation
 *
 * @example
 * ```typescript
 * const summary = summarize(buffer);
 * console.log(`${summary.rating}: ${summary.score}/100`);
 * if (summary.productionReady) {
 *   console.log(`Content: ${summary.content}`);
 * }
 * ```
 *
 * @param imageBuffer - Raw image bytes (PNG, JPEG, etc.)
 * @returns QrSummary with all key info
 */
export declare function summarize(imageBuffer: Buffer): QrSummary
/**
 * Get human-readable rating for a score
 *
 * @example
 * ```typescript
 * const rating = getRating(85); // "Excellent"
 * ```
 *
 * @param score - Score from 0-100
 * @returns Rating string (Excellent/Good/Fair/Poor)
 */
export declare function getRating(score: number): string
